# Generated by Django 5.2.12 on 2026-03-15 17:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_producto_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='hilos',
            new_name='hilo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='serial',
        ),
        migrations.AddField(
            model_name='modeloequipo',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.marca'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_ingreso',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tipofibra',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
