# Generated by Django 5.2.12 on 2026-03-16 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_movimientoinventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.IntegerField(default=5),
        ),
    ]
