# Generated by Django 5.2.12 on 2026-03-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_producto_stock_minimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='mac',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='serial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
