# Generated by Django 5.2.12 on 2026-03-19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_producto_mac_producto_serial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleIdentificador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SERIAL', 'Serial'), ('MAC', 'MAC')], max_length=10)),
                ('valor', models.CharField(max_length=120)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identificadores', to='inventario.producto')),
            ],
            options={
                'unique_together': {('producto', 'tipo', 'valor')},
            },
        ),
    ]
