# Generated by Django 5.2.12 on 2026-04-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_detalleidentificador'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleidentificador',
            name='codigo_individual',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
