# Generated by Django 5.2.12 on 2026-05-13 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_detalleidentificador_metraje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('ruc', models.CharField(blank=True, default='', max_length=20)),
                ('telefono', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('direccion', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='detalleidentificador',
            name='tipo',
            field=models.CharField(choices=[('SERIAL', 'Serial'), ('MAC', 'MAC'), ('CABLE', 'Cable')], max_length=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.proveedor'),
        ),
    ]
