# Generated by Django 5.2.12 on 2026-03-25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_detalleidentificador'),
        ('cuadrillas', '0002_asignacionidentificador'),
    ]

    operations = [
        migrations.CreateModel(
            name='BajaIdentificador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identificadores_baja', to='cuadrillas.bajamaterial')),
                ('identificador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.detalleidentificador')),
            ],
        ),
    ]
