# Generated by Django 5.2.12 on 2026-03-26 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadrillas', '0003_bajaidentificador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bajamaterial',
            name='asignacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bajas', to='cuadrillas.asignacionmaterial'),
        ),
        migrations.AlterField(
            model_name='bajamaterial',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
