# Generated by Django 5.2.12 on 2026-03-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadrillas', '0004_alter_bajamaterial_asignacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bajamaterial',
            name='detalle_mac',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bajamaterial',
            name='detalle_serial',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bajamaterial',
            name='es_equipo_activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bajamaterial',
            name='producto_codigo',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bajamaterial',
            name='producto_nombre',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
