# Generated by Django 5.2.12 on 2026-04-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadrillas', '0005_bajamaterial_campos_verificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='bajamaterial',
            name='utilizado_en',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
