# Generated by Django 5.2.12 on 2026-04-07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuadrillas', '0007_alter_bajamaterial_utilizado_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='bajamaterial',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bajas_material', to='cuadrillas.cliente'),
        ),
        migrations.AddField(
            model_name='bajamaterial',
            name='tipo_uso',
            field=models.CharField(blank=True, choices=[('Instalacion', 'Instalacion'), ('Cambio', 'Cambio'), ('Migracion', 'Migracion'), ('Soporte', 'Soporte')], default='', max_length=20),
        ),
    ]
