# Generated by Django 5.2.12 on 2026-04-08

from django.db import migrations, models
from django.db.models.functions import Lower


def normalizar(nombre):
    return ' '.join((nombre or '').strip().split()).title()


def backfill_clientes_y_tipo_uso(apps, schema_editor):
    Cliente = apps.get_model('cuadrillas', 'Cliente')
    BajaMaterial = apps.get_model('cuadrillas', 'BajaMaterial')

    # Normaliza clientes ya existentes y evita duplicados (case/espacios).
    clientes_por_clave = {}
    for cliente in Cliente.objects.all().order_by('id'):
        clave = normalizar(cliente.nombre).lower()
        if not clave:
            continue

        if clave in clientes_por_clave:
            principal = clientes_por_clave[clave]
            BajaMaterial.objects.filter(cliente_id=cliente.id).update(cliente_id=principal.id)
            cliente.delete()
        else:
            if cliente.nombre != normalizar(cliente.nombre):
                cliente.nombre = normalizar(cliente.nombre)
                cliente.save(update_fields=['nombre'])
            clientes_por_clave[clave] = cliente

    opciones = {'instalacion': 'Instalacion', 'cambio': 'Cambio', 'migracion': 'Migracion', 'soporte': 'Soporte'}

    for baja in BajaMaterial.objects.all().iterator():
        if baja.cliente_id and baja.tipo_uso:
            continue

        texto = (baja.utilizado_en or '').strip()
        if not texto:
            continue

        partes = [p.strip() for p in texto.split('-', 1)]
        tipo = ''
        cliente_nombre = ''

        if len(partes) == 2:
            tipo = opciones.get(partes[0].lower(), '')
            cliente_nombre = normalizar(partes[1])
        else:
            # Si no tiene separador, se intenta interpretar como cliente.
            cliente_nombre = normalizar(texto)

        update_fields = []

        if tipo and not baja.tipo_uso:
            baja.tipo_uso = tipo
            update_fields.append('tipo_uso')

        if cliente_nombre and not baja.cliente_id:
            cliente = Cliente.objects.filter(nombre__iexact=cliente_nombre).first()
            if not cliente:
                cliente = Cliente.objects.create(nombre=cliente_nombre)
            baja.cliente_id = cliente.id
            update_fields.append('cliente')

        if update_fields:
            baja.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('cuadrillas', '0008_cliente_bajamaterial_tipo_uso_cliente'),
    ]

    operations = [
        migrations.RunPython(backfill_clientes_y_tipo_uso, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(Lower('nombre'), name='uq_cliente_nombre_ci'),
        ),
    ]
