# Generated by Django 5.2.12 on 2026-04-08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuadrillas', '0009_backfill_cliente_tipo_uso_and_unique_ci'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bajamaterial',
            name='utilizado_en',
        ),
    ]
