# Generated by Django 5.2.12 on 2026-04-08

from django.db import migrations, models


def backfill_cliente_nombre(apps, schema_editor):
    BajaMaterial = apps.get_model('cuadrillas', 'BajaMaterial')

    for baja in BajaMaterial.objects.select_related('cliente').all().iterator():
        if baja.cliente_id and not baja.cliente_nombre:
            baja.cliente_nombre = baja.cliente.nombre
            baja.save(update_fields=['cliente_nombre'])


class Migration(migrations.Migration):

    dependencies = [
        ('cuadrillas', '0010_remove_bajamaterial_utilizado_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='bajamaterial',
            name='cliente_nombre',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.RunPython(backfill_cliente_nombre, migrations.RunPython.noop),
    ]
